### ISSUE TITLE
Fanshim on Openwrt

### ISSUE THREAD

**Issue by lucairr** [flobernd/raspi-fanshim#5]
Hi all, I used fanshim on my raspberry pi 4 for months.
Now, I m going to use my raspberry as a router with Openwrt on it.
There is a way to install fanshim on Openwrt since it doesn't use apt as package manager?
Thanks

**Comment by flobernd** [comment]
It could work if the wiringPi lib can be manually compiled for the openwrt system.

I sadly don't know if that is the case.
